DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'buildmate_app') THEN
    CREATE ROLE buildmate_app LOGIN PASSWORD 'buildmate_app_change_me';
  END IF;
END
$$;

GRANT CONNECT ON DATABASE buildmate TO buildmate_app;
GRANT USAGE ON SCHEMA public TO buildmate_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO buildmate_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO buildmate_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO buildmate_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO buildmate_app;
